Remove unnecessary `Box`
sqlparser-rs/sqlparser-rs pull request #556
Opened 2022-08-06 08:23 UTC by ever0de

Previously, the `Statement` variant seemed to be used recursively, but this is not the case now.

2022-08-11 10:34 UTC, alamb reviewed
I believe this `Box` was added in https://github.com/sqlparser-rs/sqlparser-rs/pull/540 by @5tan to save stack space

Perhaps we can add a comment somewhere to the code explaining the rationale?

2022-08-11 16:53 UTC, ever0de commented
> I believe this `Box` was added in #540 by @5tan to save stack space
> 
> Perhaps we can add a comment somewhere to the code explaining the rationale?

There was this context. thank you
I'm a little confused, but using `Box' saves stack space, but doesn't it use that much heap space? I don't know why this is better.
What should I look for to understand this?

2022-08-11 20:31 UTC, alamb commented
> What should I look for to understand this?

Here is a description of the issue that I like (though I am obviously biased :bowtie: ): https://github.com/apache/arrow-datafusion/pull/1047

2022-08-13 13:31 UTC, andygrove approved these changes

2022-08-13 13:32 UTC, andygrove requested changes
Oops ... I approved before seeing the comments from @alamb

2022-08-13 13:34 UTC, ever0de commented
> Oops ... I approved before seeing the comments from @alamb

Yes, this should be a work in progress.
However, it is still not clear whether the Query occupies a stack size large enough to be a 'Box'.
It seems that I have some understanding.

I am looking at the work @alamb linked.

2022-08-15 12:28 UTC, alamb commented
Marking as draft as we work on this issue 👍  thanks @ever0de

2022-08-15 12:54 UTC, ever0de commented
> Marking as draft as we work on this issue 👍 thanks @ever0de

thank you I was wondering if I should change it.

2022-08-26 07:00 UTC, ever0de commented
hello. At the current main <https://github.com/sqlparser-rs/sqlparser-rs/commit/72559e9b6298f39c9ab2a084b5e1cd11d3fb6c6d> commit, I tried running the sql syntax of #540 PR, but it fails with stack overflow. Maybe I've missed something?

### Using Command

```shell
x=286 ; echo 'print("SELECT * FROM {}ttt{}".format("("*'$x',")"*'$x'))' | python3 > test.sql && cargo run --example cli --manifest-path Cargo.toml test.sql --snowflake
```

2022-08-31 13:49 UTC, 5tan commented
Hi friends! Currently `sizeof::<Query>()=592`. If we unbox the query body back (revert my changes), then `sizeof::<Query>()=1360`.

2022-08-31 14:18 UTC, andygrove commented
> Perhaps we can add a comment somewhere to the code explaining the rationale?

@ever0de Would you mind updating this PR to revert the changes but add a comment instead?

2022-08-31 14:50 UTC, ever0de commented
> > Perhaps we can add a comment somewhere to the code explaining the rationale?
> 
> @ever0de Would you mind updating this PR to revert the changes but add a comment instead?

First of all, I understand that this PR is a bad fix.
I will close the PR first, and then bring it with me if there is an improvement plan.
Thanks for the good information.

Can I close this PR?

2022-08-31 14:53 UTC, andygrove commented
> Can I close this PR?

Yes, please go ahead! Thanks.

2022-08-31 14:53 UTC, closed without merging