Parse alter table drop primary key
sqlparser-rs/sqlparser-rs pull request #682
Opened 2022-10-21 03:40 UTC by ding-young

## Issue
resolves #591

2022-10-29 22:01 UTC, AugustoFKL requested changes

2022-10-29 22:01 UTC, AugustoFKL commented on src/parser.rs
> +            } else if self.parse_keyword(Keyword::PRIMARY) {
@ding-young `ALTER TABLE tb DROP PRIMARY` isn't allowed and, therefore, shouldn't be acceptable. 

The `let _` in the next line is permissive over this.

Also, I think this is a MySQL-specific statement. Could you please add the validation to accept only `MySQL` and `GenericDialect`, please?

2022-10-31 18:34 UTC, alamb reviewed
@ding-young  do you have time to implement @AugustoFKL 's suggestion? Otherwise this PR  looks good to me

2022-10-31 19:15 UTC, ding-young commented
> @ding-young  do you have time to implement @AugustoFKL 's suggestion? Otherwise this PR  looks good to me

Yes, I'll work on it soon.

2022-10-31 20:36 UTC, ding-young commented
@AugustoFKL Thank you for feedback. I changed the code 😃

2022-11-01 02:42 UTC, AugustoFKL approved these changes
LGTM

@alamb ready for approval :)

2022-11-02 14:15 UTC, alamb approved these changes

2022-11-02 14:15 UTC, alamb commented
Thanks @ding-young  and @AugustoFKL !

2022-11-02 14:15 UTC, merged